backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

#local_backend: true

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Oldalak"
    files:
      - file: "site/content/ovodai_aa/_index.md"
        label: "Óvodai jelek - A, Á"
        name: "ovodai_aa"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_b/_index.md"
        label: "Óvodai jelek - B"
        name: "ovodai_b"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_ccs/_index.md"
        label: "Óvodai jelek - C, Cs"
        name: "ovodai_ccs"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_d/_index.md"
        label: "Óvodai jelek - D"
        name: "ovodai_d"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_ee/_index.md"
        label: "Óvodai jelek - E, É"
        name: "ovodai_ee"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_f/_index.md"
        label: "Óvodai jelek - F"
        name: "ovodai_f"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_ggy/_index.md"
        label: "Óvodai jelek - G, Gy"
        name: "ovodai_ggy"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_h/_index.md"
        label: "Óvodai jelek - H"
        name: "ovodai_h"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_i/_index.md"
        label: "Óvodai jelek - I"
        name: "ovodai_i"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_k/_index.md"
        label: "Óvodai jelek - K"
        name: "ovodai_k"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_l/_index.md"
        label: "Óvodai jelek - L"
        name: "ovodai_l"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image
      - file: "site/content/ovodai_m/_index.md"
        label: "Óvodai jelek - M"
        name: "ovodai_m"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image  
      - file: "site/content/ovodai_nny/_index.md"               
        label: "Óvodai jelek - N, Ny"
        name: "ovodai_nny"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_oo/_index.md"        
        label: "Óvodai jelek - O, Ö"
        name: "ovodai_oo"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_p/_index.md"
        label: "Óvodai jelek - P"
        name: "ovodai_p"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_r/_index.md"
        label: "Óvodai jelek - R"
        name: "ovodai_r"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_ssz/_index.md"
        label: "Óvodai jelek - S, Sz"
        name: "ovodai_ssz"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_t/_index.md"
        label: "Óvodai jelek - T"
        name: "ovodai_t"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_uu/_index.md"
        label: "Óvodai jelek - U, Ü"
        name: "ovodai_uu"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_v/_index.md"
        label: "Óvodai jelek - V"
        name: "ovodai_v"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/ovodai_zzs/_index.md"
        label: "Óvodai jelek - Z, Zs"
        name: "ovodai_zzs"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jel kategóriája
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: img
                    widget: image 
      - file: "site/content/arak/_index.md"
        label: "Árak"
        name: "arak"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Óvodai jelek árai
            name: arak_text
            widget: list
            fields:
              - label: Árak
                name: arak
                widget: string                                                                                                                                                                                                                                                                               
      - file: "site/content/ajanlatkeres/_index.md"
        label: "Árajánlatkérés"
        name: "ajanlatkeres"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Saját termékek listája
            name: lehetosegek
            widget: list
            fields:
              - label: Saját termékek listája
                name: opcio
                widget: string
          - label: Óvodai jelek listája
            name: ovodaijelek
            widget: list
            fields:
              - label: Óvodai jelek listája
                name: opt
                widget: string